const baseAPIUrl = "http://127.0.0.1:5500/apiv1";
const gens = ["gen1", "gen2", "gen3", "gen4", "gen5", "gen6", "gen7", "gen8", "gen9"];
const tiers = [
        "ou",
        "ubers",
        "pu",
        "nu",
        "lc",
        "uu",
        "ru",
        "2v2doubles",
        "doubles",
        "anythinggoes",
        "almostanyability",
        "balancedhackmons",
        "battlefactory",
        "battlespotsingles",
        "battlespotdoubles",
        "battlespotspecial",
        "bssfactory",
        "budoubles",
        "busingles",
        "camomons",
        "challengecup",
        "challengecup1v1",
        "doublescustomgame",
        "doublesou",
        "doublesubers",
        "doublesuu",
        "hackmonscup",
        "inversebattle",
        "lcuu",
        "linked",
        "monotype",
        "natureswap",
        "nfe",
        "ounomega",
        "randombattle",
        "randomdoublesbattle",
        "randomtriplesbattle",
        "stabmons",
        "smogontriples",
        "tiershift",
        "ultrakalosclassic",
        "vcg2018",
        "vgc2014",
        "vgc2015",
        "vgc2016",
        "vgc2017",
        "vgc2019",
        "vgc2020",
        "zu",
        "doubleslc"
      ];

      export default { baseAPIUrl, gens, tiers }